- id: mode_nuit
  alias: Automation Mode Nuit
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_gautier
        click_type: single
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_manon
        click_type: single
  condition:
      - condition: state
        entity_id: input_boolean.is_jour
        state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.bandeau_lit
        brightness: 255 
    - service: script.turn_off_all_lights_expected_bedroom
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.is_jour
      
- id: mode_jour
  alias: Automation Mode Jour
  trigger:
    platform: state
    entity_id: cover.volet_chambre
    to: 'open'
  action:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.is_jour
    
      
- id: mode_absence
  alias: Automation Mode Absence
  trigger:
    - platform: state
      entity_id: binary_sensor.nut_tracker_gautier
      from: 'on'
      to: 'off'
      for: 
        minutes: 2
    - platform: state
      entity_id: binary_sensor.nut_tracker_manon
      from: 'on'
      to: 'off'
      for: 
        minutes: 2
  condition:
      condition: and
      conditions:
      - condition: state
        entity_id: binary_sensor.nut_tracker_manon
        state: 'off'
      - condition: state
        entity_id: binary_sensor.nut_tracker_gautier
        state: 'off'
  action:
    - service: light.turn_off
      data:
       entity_id: all
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.presence

- id: mode_presence
  alias: Automation Mode Presence
  trigger:
    - platform: state
      entity_id: binary_sensor.nut_tracker_manon
      from: 'off'
      to: 'on'
      for: 
        minutes: 2
    - platform: state
      entity_id: binary_sensor.nut_tracker_gautier
      from: 'off'
      to: 'on'
      for: 
        minutes: 2
  condition:
      condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.nut_tracker_gautier
        state: 'on'
      - condition: state
        entity_id: binary_sensor.nut_tracker_manon
        state: 'on'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.presence
        
        
      
#==============================================================================#
#===================================== NOTIF ==================================#
#==============================================================================# 


- id: daily_recap_manon
  alias: Automation daily info manon
  trigger:
    platform: time
    at: "07:30:00"
  action:
    - service: telegram_bot.send_message
      data:
        message: "<b>&#x1F44B;&#x1F3FC; Coucou ma Hey Oh ! &#x2764;&#xFE0F;</b>\n\n&#x1F321;&#xFE0F; Aujourd'hui il fera au maximum {{ states('sensor.dark_sky_daytime_high_apparent_temperature_0d') }}°C et au minimum {{ states('sensor.dark_sky_overnight_low_apparent_temperature_0d')}}°C &#x1F321;&#xFE0F;\n&#x1F324;&#xFE0F; Type de météo aujourd'hui : {{ states('sensor.dark_sky_summary_0d') }}&#x1F324;\n&#x2600; Levé du soleil : {{ states('sensor.nextsunrise') }}\n&#x1F319; Couché du soleil : {{ states('sensor.nextsunset')}}\n&#xFE0F;\n\n&#x1F47C;&#x1F3FB; Nous fêtons les : {{ states.calendar.agenda_goguigaut.attributes.message }}"
        target:
          - 432161160

- id: daily_recap_gautier
  alias: Automation daily info Gautier
  trigger:
    platform: time
    at: "7:30:00"
  action:
    - service: telegram_bot.send_message
      data:
        message: "<b> &#x1F44B; Salut Gautier ! &#x1F44B; </b>\n\n&#x1F321;&#xFE0F; Aujourd'hui il fera au maximum {{ states('sensor.dark_sky_daytime_high_apparent_temperature_0d') }}°C et au minimum {{ states('sensor.dark_sky_overnight_low_apparent_temperature_0d')}}°C &#x1F321;&#xFE0F;\n&#x1F324;&#xFE0F; Type de météo aujourd'hui : {{ states('sensor.dark_sky_summary_0d') }}&#x1F324;\n&#x2614;Chance de précipitation : {{ states('sensor.dark_sky_precip_probability_0d') }}%\n&#x2600; Levé du soleil : {{ states('sensor.nextsunrise') }}\n&#x1F319; Couché du soleil : {{ states('sensor.nextsunset')}}\n&#xFE0F;\n\n&#x1F47C;&#x1F3FB; Nous fêtons les : {{ states.calendar.agenda_goguigaut.attributes.message }}"
        target:
          - 333243974

- id: trajet_travail_gautier
  alias: Automation notifs trajet travail Gautier
  trigger:
    platform: state
    entity_id: binary_sensor.door_entree
    from: 'off'
    to: 'on'
  condition:
    condition: time
    after: '07:50:00'
    before: '09:00:00'
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: telegram_bot.send_message
      data:
        message: "&#x1F3CE; Domicile -> Travail : {{ states('sensor.google_travel_time_driving') }} minutes &#x1F3CD;"
        target:
          - 333243974
          
- id: porte_ouverte
  alias: Automation notifs porte
  trigger:
    platform: state
    entity_id: binary_sensor.door_entree
    from: 'off'
    to: 'on'
  action:
    - service: telegram_bot.send_message
      data:
        message: "&#x1F6AA; Porte d'entrée ouverte &#x1F6AA;"
        target:
          - 432161160
          - 333243974

- id: porte_ouverte_5_min
  alias: Automation notifs porte
  trigger:
    platform: state
    entity_id: binary_sensor.door_entree
    to: 'on'
    for:
      minutes: 5
  action:
    - service: telegram_bot.send_message
      data:
        message: "&#x1F6AA; &#x1F6A8; Porte d'entrée ouverte depuis 5 minutes &#x1F6A8; &#x1F6AA;"
        target:
          - 432161160
          - 333243974
          
- id: bienvenue_gautier
  alias: Message accueil Gautier
  trigger: 
    platform: state
    entity_id: person.gautier
    to: 'home'
    for: 
      minutes: 0
      seconds: 30
  action: 
    service: tts.google_cloud_say
    entity_id: media_player.nesthub
    data:
      message: "Salut chef ! Comme d'habitude, salade, tomate, onion ?"
      
- id: bienvenue_manon
  alias: Message accueil Manon
  trigger: 
    platform: state
    entity_id: person.manon
    to: 'home'
    for: 
      minutes: 0
      seconds: 30
  action: 
    service: tts.google_cloud_say
    entity_id: media_player.nesthub
    data:
      message: 'Coucou blablablu ! Met du coco et on demarre !' 
      
          
- id: henry_end
  alias: Automation notifs fin de nettoyage
  trigger:
    platform: state
    entity_id: vacuum.xiaomi_vacuum_cleaner
    # from: 'cleaning'
    to: 'docked'
  action:
    - service: telegram_bot.send_message
      data:
        message: "&#x1F916; Henry a fini son nettoyage &#x1F916;"
        target:
          - 432161160
          - 333243974
          
#==============================================================================#
#===================================== LIGHTS =================================#
#==============================================================================#

- id: motion_detection_wc_on
  alias: Automation Light WC On
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_wc
    to: 'on'
  action:
    service: light.turn_on
    data_template:
      entity_id: light.wc
      brightness: >-
            {% if is_state('input_boolean.is_jour', 'on') %}
              {{254 | int}}
            {% else %}
              {{40|int}}
            {% endif %}

      
- id: motion_detection_wc_off
  alias: Automation Light WC Off
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_wc
    from: 'on'
    to: 'off'
    for:
      seconds: 30
  action:
    service: light.turn_off
    data:
      entity_id: light.wc

      
- id: WC_caca_start
  alias: Automation WC caca start
  trigger:
    platform: state
    entity_id: binary_sensor.door_wc
    from: 'on'
    to: 'off'
  condition:
    condition: state
    entity_id: binary_sensor.motion_sensor_wc
    state: 'on'
  action:
    - service: automation.turn_off
      data:
        entity_id: automation.automation_light_wc_off
      
- id: WC_caca_end
  alias: Automation WC caca end
  trigger:
    platform: state
    entity_id: binary_sensor.door_wc
    from: 'off'
    to: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: light.wc
    - service: automation.turn_on
      data:
        entity_id: automation.automation_light_wc_off

- id: spot_sdb_off
  alias: Turn off spot sdb
  trigger:
    - platform: state
      entity_id: light.sdb
      from: 'on'
      to: 'off'
  action:
   - service: light.turn_off
     data:
      entity_id: light.miroir_sdb_gauche
   - service: light.turn_off
     data:
      entity_id: light.miroir_sdb_droite

- id: pre_dodo
  alias: Automation Pré-dodo
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_gautier
        click_type: single
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_manon
        click_type: single
  condition:
      - condition: state
        entity_id: input_boolean.is_jour
        state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.bandeau_lit
        brightness: 100 
    - service: script.turn_off_all_lights_expected_bedroom
    
- id: inter_double_salon_left
  alias: inter salon gauche
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_left
        click_type: single
  action:
    - service: light.toggle
      data:
        entity_id: light.salon

- id: inter_double_salon_right
  alias: inter salon gauche
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_right
        click_type: single
  action:
    - service: light.toggle
      data:
        entity_id: 
          - light.cuisine
          - light.hall_entree
        
        
- id: dodo
  alias: Automation dodo
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_gautier
        click_type: long_click_press
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_manon
        click_type: long_click_press
  action:
    - service: light.turn_off
      data:
        entity_id: all
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.is_jour
        
        
        
        
# Quand je commence à 7h - départ 6h15
# 7h30 - 6h45
# 8h - 7h15
# 8h30 - 7h45
# 13h30 - 12h45        
        
- id: update_travel_time
  alias: "Update Gautier temps de trajet"
  trigger:
    - platform: time_pattern
      minutes: '/5'
  condition:
    - condition: time
      after: '07:30:00'
      before: '08:45:00'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: homeassistant.update_entity
      entity_id: sensor.google_travel_time_driving
      
#==============================================================================#
#===================================== ALARME =================================#
#==============================================================================#

- id: alarme_fenetres
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.door_window_1
        - binary_sensor.door_window_2
        - binary_sensor.door_window_3
        - binary_sensor.door_window_4
        - binary_sensor.door_window_5_chambre
        - binary_sensor.door_window_6_chambre
        - binary_sensor.door_window_7_gedeon
      from: 'off'
      to: 'on'
  condition:
      - condition: state
        entity_id: input_boolean.presence
        state: 'off'
  action:
    - service: telegram_bot.send_message
      data_template:
        message: "&#x1F6A8; Alarme Intrusion {{ trigger.to_state.attributes.friendly_name }} &#x1F6A8;" 
        target:
          - 333243974  
      
- id: alarme_scooter
  trigger:
    - platform: event
      event_type: xiaomi_aqara.movement
      event_data:
        entity_id: binary_sensor.vibration_scooter
        movement_type: vibrate
  action:
    - service: telegram_bot.send_message
      data_template:
        message: "&#x1F6A8; &#x1F3CD;	Alarme Scooter &#x1F3CD; &#x1F6A8;" 
        target:
          - 333243974      
#==============================================================================#
#===================================== DEBUG ==================================#
#==============================================================================#

- id: debug_nut_gautier
  trigger:
    - platform: state
      entity_id: binary_sensor.nut_tracker_gautier
      from: 'on'
      to: 'off'
  action:
    - service: telegram_bot.send_message
      data:
        message: "NUT Gautier absent" 
        target:
          - 333243974

- id: debug_nut_manon
  trigger:
    - platform: state
      entity_id: binary_sensor.nut_tracker_manon
      from: 'on'
      to: 'off'
  action:
    - service: telegram_bot.send_message
      data:
        message: "NUT Manon absent" 
        target:
          - 333243974
