# Example configuration.yaml entry
default_config:

zone: !include zone.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include_dir_merge_list scripts/
sensor: !include sensor/sensor.yaml
switch: !include switch.yaml
input_boolean: !include sensor/input_boolean.yaml
google_assistant: !include sensor/google.yaml
device_tracker: !include sensor/device_tracker.yaml
light: !include sensor/light.yaml
scene: !include scene.yaml
stream:
python_script:
discovery:
frontend:
  themes: !include_dir_merge_named themes/
  


http:
  cors_allowed_origins:
    - !secret base_url
    - !secret domaine_url
    - https://cast.home-assistant.io

tts:
  - platform: google_cloud
    key_file: google_tts.json
    language: fr-FR
    gender: female
    speed: 0.75
    voice: fr-FR-Wavenet-A

        
telegram_bot:
  - platform: webhooks
    api_key: !secret telegram_api_key
    parse_mode: html
    allowed_chat_ids:
      - !secret telegram_manon
      - !secret telegram_gautier
      
media_player:
  # - platform: xboxone
  #   device: !secret xbox_one
  #   name: Xbox One
    
cast:
  media_player:
    - host: 192.168.2.20 #NEST
    - host: 192.168.2.15 #GMini SDB
    - host: 192.168.2.11 #GHome Chambre
    
xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - mac: !secret xiaomi_mac_gateway
      key: !secret xiaomi_key_gateway
      host: 192.168.2.14
      
yeelight:
  devices:
    192.168.2.19:
      name: Yeelight Cuisine
      
# linky:
#   - username: !secret mail_gautier
#      password: !secret linky_password

shelly:
  discovery: true
  sensors:
    - all 
    
netatmo:
  client_id: !secret netatmo_client_id
  client_secret: !secret netatmo_client_secret

  
vacuum:
  - platform: xiaomi_miio
    host: 192.168.2.70
    token: !secret xiaomi_vacuum_token
    
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

#spotcast:
#  username: !secret spotify_username
#  password: !secret spotify_password

camera:
  - platform: foscam
    ip: 192.168.2.18
    port: 88
    username: !secret foscam_username
    password: !secret foscam_password
    

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

    
weather:
  - platform: darksky
    api_key: !secret dark_sky_api_key
    
remote:
  - platform: harmony
    name: Harmony Salon
    host: 192.168.2.16
