 
- id: dodo
  alias: Automation dodo
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_gautier
        click_type: long_click_press
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_manon
        click_type: long_click_press
  action:
    - service: light.turn_off
      data:
        entity_id: all
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.is_jour
      
        
# Quand je commence à 7h - départ 6h15
# 7h30 - 6h45
# 8h - 7h15
# 8h30 - 7h45
# 13h30 - 12h45        
        
- id: update_travel_time
  alias: "Update Gautier temps de trajet"
  trigger:
    - platform: time_pattern
      minutes: '/5'
  condition:
    - condition: time
      after: '07:30:00'
      before: '08:45:00'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: homeassistant.update_entity
      entity_id: sensor.google_travel_time_driving
      

